### ISSUE TITLE
About setmap() function error

### ISSUE THREAD

**Issue by lihp6207** [simondlevy/BreezySLAM#23]
Hi, Simon :
I have the same issue with "https://github.com/simondlevy/BreezySLAM/issues/17".
But when I use the function setmap(). ex: slam.setmap(mapbytes)
The following error appeared:

------------------------------------------------------------------------------------------------------------
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 130, in setmap
    self.map.set(mapbytes)
AttributeError: 'pybreezyslam.Map' object has no attribute 'set'
------------------------------------------------------------------------------------------------------------
It seems cannot find pybreezyslam.Map.set().
Did I have a wrong usage?
Thank you!

**Comment by andrewda** [comment]
Running into the same issue. Any updates?

**Comment by simondlevy** [comment]
Make sure you've downloaded the latest version of BreezySLAM and are running Python 3.  I've stopped supporting Python 2.

**Comment by andrewda** [comment]
Ah gotcha, that'd be the problem. I was using Python 2.

**Comment by simondlevy** [comment]
There could still be a problem -- if so, I'll be happy to look into it.

**Comment by andrewda** [comment]
Just got home and was able to test it with Python 3 -- seems the issue is still present, same error as before.

**Comment by lihp6207** [comment]
Hi, simondlevy and andrewda!
I have solved the problem not long ago by using slam.map.__init__ function instead of slam.setmap.
EX:
    slam = breezyslam.algorithms.RMHC_SLAM(lidar, MAP_SIZE_PIXELS, MAP_SIZE_METERS)
    slam.map.__init__(MAP_SIZE_PIXELS, MAP_SIZE_METERS, mapbytes)

You can try it !
Thanks!

**Comment by andrewda** [comment]
Thank you, @lihp6207, `slam.map.__init__()` worked! Definitely still a plus to get the `set()` method working properly, but thanks again for the fix in the meantime!

**Comment by lihp6207** [comment]
It's my pleasure!

**Comment by simondlevy** [comment]
Thanks for figuring this out, lihp6207!  I've fixed slam.setmap() and tested it, but I'd appreciate it if you guys would give it a try and let me know if it's still not working.

**Comment by andrewda** [comment]
Works like a charm, appreciate it!
