### ISSUE TITLE
Mapping is nothing like example

### ISSUE THREAD

**Issue by OneQuestion** [simondlevy/BreezySLAM#37]
I can't get mapping to work as it looks in main page's image. Mine always gets blurry and shadowy when I move to other room. Only current one looks fine.
![slam](https://user-images.githubusercontent.com/46217499/50536765-90771500-0b60-11e9-99e4-f468c8c5b014.png)

**Comment by abylikhsanov** [comment]
What odometry are you providing? It seems that you have a poor Odometry/IMU readings and that's why you get those blurry lines, just my assumption.

**Comment by OneQuestion** [comment]
I do not use any odometry, but I almost fixed the issue by setting QUALITY to 1
