### ISSUE TITLE
C++ Demo Examples not working

### ISSUE THREAD

**Issue by Meghadoot** [simondlevy/BreezySLAM#38]
I have cd to BreezySLAM/cpp, and do 'sudo make install'. But when I then cd to BreezySLAM/examples and do 'make cpptest', (I have correctly set the LIBDIR paths in both cpp and examples folder's makefiles)I got error as shown in snap. 
![demo_compilation_issue](https://user-images.githubusercontent.com/25079922/50599724-30a9a280-0eaf-11e9-8299-d5cd71478ed6.png)
 
Can you give me some suggestion? Thanks in advance!

**Comment by Meghadoot** [comment]
On the other hand, Pytest works without any issues(can be seen in following snap)

![works_pytest](https://user-images.githubusercontent.com/25079922/50600358-1f619580-0eb1-11e9-8023-99adfed56eac.png)

**Comment by simondlevy** [comment]
From the instructions:

**You may also need to add the following line to your ~/.bashrc file:**

```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib```

**Comment by Meghadoot** [comment]
Yes I already have updated ~/.bashrc as per instructions.
still error persists ..

**Comment by Meghadoot** [comment]
Thanks. Now resolved it.
Issue was with path variable.
